[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "curator"
authors = [{name = "Gagan Kumar", email = "curator@redhat.com"}]
dynamic = ["version", "description"]
